workspace(name = "com_github_ray_streaming")

# LOAD RAY WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
ray_version = "94caac87222784a36b76f9ee2e607fd796217477"
http_archive(
        name="com_github_ray_project_ray",
        strip_prefix = "ray-{}".format(ray_version),
        urls = ["https://github.com/ray-project/ray/archive/{}.zip".format(ray_version)],
        sha256 = "69a2dc6e0d78e14758ef60ab2eb34b99c88f3e1c6292b1181dbf83e164272032",
)


load("@com_github_ray_project_ray//bazel:ray_deps_setup.bzl", "ray_deps_setup")

ray_deps_setup()

load("@com_github_ray_project_ray//bazel:ray_deps_build_all.bzl", "ray_deps_build_all")

ray_deps_build_all()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

load("//bazel:streaming_deps_setup.bzl", "streaming_deps_setup")

streaming_deps_setup()

load("@bazel_skylib//lib:versions.bzl", "versions")

# When the bazel version is updated, make sure to update it
# in setup.py as well.
versions.check(minimum_bazel_version = "4.2.1")
