workspace(name = "com_github_ray_streaming")

# LOAD RAY WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
ray_version = "ray-support-internal-deps-bazel-include"
http_archive(
        name="com_github_ray_project_ray",
        strip_prefix = "ray-{}".format(ray_version),
        urls = ["https://github.com/ray-project/ray/archive/refs/heads/{}.zip".format(ray_version)],
        sha256 = "3bbcadcaf9f78d69e055e19ef38654371eee009829eb49e7766dcd5cfd8397b4",
)


load("@com_github_ray_project_ray//bazel:ray_deps_setup.bzl", "ray_deps_setup")

ray_deps_setup()

#load("//bazel:streaming_deps_setup.bzl", "streaming_deps_setup")

#streaming_deps_setup()
load("@com_github_ray_project_ray//bazel:ray_deps_build_all.bzl", "ray_deps_build_all")

ray_deps_build_all()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

load("@bazel_skylib//lib:versions.bzl", "versions")

# When the bazel version is updated, make sure to update it
# in setup.py as well.
versions.check(minimum_bazel_version = "4.2.1")
