# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mobius.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mobius.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cmobius.proto\x1a\x1cgoogle/api/annotations.proto\"\x19\n\x0cInferRequest\x12\t\n\x01x\x18\x01 \x03(\x02\"\x1a\n\rInferResponse\x12\t\n\x01y\x18\x01 \x03(\x02\x32z\n\x06Mobius\x12<\n\x05Infer\x12\r.InferRequest\x1a\x0e.InferResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\"\t/v1/infer:\x01*\x12\x32\n\x0bInferStream\x12\r.InferRequest\x1a\x0e.InferResponse\"\x00(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_INFERREQUEST = _descriptor.Descriptor(
  name='InferRequest',
  full_name='InferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='InferRequest.x', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=71,
)


_INFERRESPONSE = _descriptor.Descriptor(
  name='InferResponse',
  full_name='InferResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='y', full_name='InferResponse.y', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['InferRequest'] = _INFERREQUEST
DESCRIPTOR.message_types_by_name['InferResponse'] = _INFERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InferRequest = _reflection.GeneratedProtocolMessageType('InferRequest', (_message.Message,), dict(
  DESCRIPTOR = _INFERREQUEST,
  __module__ = 'mobius_pb2'
  # @@protoc_insertion_point(class_scope:InferRequest)
  ))
_sym_db.RegisterMessage(InferRequest)

InferResponse = _reflection.GeneratedProtocolMessageType('InferResponse', (_message.Message,), dict(
  DESCRIPTOR = _INFERRESPONSE,
  __module__ = 'mobius_pb2'
  # @@protoc_insertion_point(class_scope:InferResponse)
  ))
_sym_db.RegisterMessage(InferResponse)



_MOBIUS = _descriptor.ServiceDescriptor(
  name='Mobius',
  full_name='Mobius',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=101,
  serialized_end=223,
  methods=[
  _descriptor.MethodDescriptor(
    name='Infer',
    full_name='Mobius.Infer',
    index=0,
    containing_service=None,
    input_type=_INFERREQUEST,
    output_type=_INFERRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\016\"\t/v1/infer:\001*')),
  ),
  _descriptor.MethodDescriptor(
    name='InferStream',
    full_name='Mobius.InferStream',
    index=1,
    containing_service=None,
    input_type=_INFERREQUEST,
    output_type=_INFERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOBIUS)

DESCRIPTOR.services_by_name['Mobius'] = _MOBIUS

# @@protoc_insertion_point(module_scope)
