# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mobius_pb2 as mobius__pb2


class MobiusStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Infer = channel.unary_unary(
        '/Mobius/Infer',
        request_serializer=mobius__pb2.InferRequest.SerializeToString,
        response_deserializer=mobius__pb2.InferResponse.FromString,
        )
    self.InferStream = channel.stream_stream(
        '/Mobius/InferStream',
        request_serializer=mobius__pb2.InferRequest.SerializeToString,
        response_deserializer=mobius__pb2.InferResponse.FromString,
        )


class MobiusServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Infer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InferStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MobiusServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Infer': grpc.unary_unary_rpc_method_handler(
          servicer.Infer,
          request_deserializer=mobius__pb2.InferRequest.FromString,
          response_serializer=mobius__pb2.InferResponse.SerializeToString,
      ),
      'InferStream': grpc.stream_stream_rpc_method_handler(
          servicer.InferStream,
          request_deserializer=mobius__pb2.InferRequest.FromString,
          response_serializer=mobius__pb2.InferResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Mobius', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
