name: BAZEL-BUILD-AND-TEST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  streaming-cpp-test:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install bazel
      run: sudo sh scripts/install-bazel.sh

    - name: Build streaming and test
      run: sh -c "bash streaming/buildtest.sh"
