name: BAZEL-BUILD-AND-TEST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-with-bazel:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Download JDK
      # You may pin to the exact commit or the version.
      # uses: sormuras/download-jdk@7b5671938c6755cc645110aaa35bc5d269112f23
      uses: sormuras/download-jdk@1.1.2
      with:
        # Feature version number or project name of the JDK to download from https://jdk.java.net
        feature: 18 # default is 16

    - name: build-and-test
      run: cd streaming && bazel test //:all
