name: debian-manylinux-building

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  streaming-debian-manylinux-pipeline:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_24_x86_64

    steps:
    - uses: actions/checkout@v2

    - name: Apt get update and Install bazel
      run:  |
            cp /etc/apt/sources.list{,.bak}
            cp .github/sources.list /etc/apt/sources.list
            apt-get update
            apt-get install -yq wget openjdk-8-jdk zlib1g-dev zip
            apt-get install -yq gcc g++
            sh scripts/install-bazel.sh

    - name: Streaming python manylinux
      run: sh -c "bash streaming/python/build_wheels.sh"
