name: macos-building

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  streaming-mac-pipeline:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install basics
      run: |
           brew update
           brew install --cask homebrew/cask-versions/adoptopenjdk8

    - name: Install bazel
      run:  |
            if [ "$RUNNER_OS" == "Linux" ]; then
                  export OSTYPE="linux-gnu"
            elif [ "$RUNNER_OS" == "macOS" ]; then
                  export OSTYPE="darwin"
            else
                  echo "$RUNNER_OS not supported"
                  exit 1
            fi
            sudo sh scripts/install-bazel.sh

            #- name: Install ray wheel
            #  run: |
            #       which python3
            #       python3 --version
            #       which python3.8
            #       python3.8 -m pip3 install https://ray-mobius-us.oss-us-west-1.aliyuncs.com/ci/macos/ray-2.0.0.dev0-cp38-cp38-macosx_11_0_x86_64.whl

            #- name: Streaming python test
            #  run: sh -c "bash streaming/buildtest.sh --test_categories=streaming_python"

    - name: Install OSS
      run: |
           sh scripts/ossutils.sh install

    - name: Streaming java test
      env:
           OSS_HOST: oss-us-west-1.aliyuncs.com
           OSS_BUCKET: ray-mobius-us
           OSS_ID: ${{ secrets.OSS_ID }}
           OSS_KEY: ${{ secrets.OSS_KEY }}
      run: sh -c "bash streaming/buildtest.sh --test_categories=streaming_java"

    - name: Streaming cpp test
      env:
           OSS_HOST: oss-us-west-1.aliyuncs.com
           OSS_BUCKET: ray-mobius-us
           OSS_ID: ${{ secrets.OSS_ID }}
           OSS_KEY: ${{ secrets.OSS_KEY }}
      run: sh -c "bash streaming/buildtest.sh --test_categories=streaming_cpp"
