name: BAZEL-BUILD-AND-TEST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  streaming-cpp-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: docker.io/library/ubuntu:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install bazel
      run:  |
            apt-get install -yq wget gcc openjdk-8-jdk python3.7 python3.7-dev
            sh scripts/install-bazel.sh

    - name: Build streaming and test
      run: sh -c "bash streaming/buildtest.sh"
